### ISSUE TITLE
Large sample dataset (Canada)

### ISSUE THREAD

**Issue by david-i-berry** [opencdms/opencdms-data-layer#4]
As a developer I need representative test data to ingest into the database and to test.

- [ ] Reference data / code lists
- [ ] Sample station and sensor metadata
- [ ] Sample observation data for long time period (time slice)
- [ ] Sample observation data at multiple locations for single (or constrained) period of time (spatial slice)
- [ ] Sample provenance and processing metadata
- [ ] Link to source and license

**Comment by david-i-berry** [comment]
The initial test data set is large (24 GB), github may not be the best location for this. I've uploaded a sample to the opencdms-test-data repo (https://github.com/opencdms/opencdms-test-data) under the cdm branch. This doesn't include any provenance or processing metadata or sensor metadata.

**Comment by isedwards** [comment]
Let's continue this issue for sample data in a future sprint

**Comment by isedwards** [comment]
Closed by https://github.com/opencdms/opencdms-test-data/pull/54
