### ISSUE TITLE
Data model documentation incl. build and sample data from SURFACE

### ISSUE THREAD

**Issue by david-i-berry** [opencdms/opencdms-data-layer#5]

**Comment by david-i-berry** [comment]
Developer and admin documentation on:

- [ ] build and deployment of container
- [ ] database initialisation
- [ ] ingest of sample test data
- [ ] search and retrieval of test data

Note, the users will not directly access the database but will do so via either API calls or via the web app.

**Comment by david-i-berry** [comment]
See https://github.com/wmo-im/tt-cdm/tree/v0.1.dev/data-model for initial documentation of CDM logical data model.

**Comment by isedwards** [comment]
Completed by https://github.com/wmo-im/tt-cdm/pull/14 and
https://github.com/opencdms/pyopencdms/pull/7
